backend:
  name: github
  repo: Xin1896/ji3my-xyz-blog
  branch: master
  base_url: https://ji3my.xyz
  auth_endpoint: /api/callback

media_folder: "assets/img/posts"
public_folder: "/assets/img/posts"

locale: zh_Hans

collections:
  - name: "posts"
    label: "博客文章"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss ZZ", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss"}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "正文", name: "body", widget: "markdown"}
